#
# setup certbot
#
- name: enable repos
  command: "yum-config-manager --enable {{ item }}"
  with_items: "{{ certbot_repos }}"
  tags:
    - certbot
    - certbot_setup

- name: install certbot dependencies
  yum:
    name: "{{ certbot_dependencies }}"
    state: present
  tags:
    - certbot
    - certbot_setup

- name: install certbot
  yum:
    name: "{{ certbot_packages }}"
    state: present
  tags:
    - certbot
    - certbot_setup

- name: run certbot
  shell: certbot --nginx certonly -d {{ item }} --expand --noninteractive --agree-tos --email {{ certbot_email }}
  with_items: "{{ certbot_sites[inventory_hostname] | default([]) }}"
  tags:
    - certbot
    - certbot_generate

- name: create certbot cron
  cron:
    name: certbot renew
    minute: 0
    hour: 0,12
    job: "certbot renew --nginx-ctl {{ certbot_nginx_ctl }} --nginx-server-root {{ certbot_nginx_server_root }} {{ certbot_additional_options }} --noninteractive --post-hook 'systemctl restart nginx'"
  tags:
    - certbot
    - certbot_setup

# TODO: need refine: https://github.com/certbot/certbot/issues/4937
- name: fix for certbot cron cannot find nginx binary
  file:
    src: /usr/sbin/nginx
    dest: /usr/bin/nginx
    state: link
  ignore_errors: yes
  tags:
    - certbot
    - certbot_setup
